#creation des namespaces

apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    name: prod

---

apiVersion: v1
kind: Namespace
metadata:
  name: preprod
  labels:
    name: preprod

---

apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev

--- #Creation des services

apiVersion: v1
kind: Service
metadata:
  name: flaskapp-deployment-prod
  namespace: prod
  labels:
    app: flask-svc
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
  - port: 5005
    protocol: TCP
    targetPort: 5005

---

apiVersion: v1
kind: Service
metadata:
  name: flaskapp-deployment-prod
  namespace: preprod
  labels:
    app: flask-svc
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
  - port: 5005
    protocol: TCP
    targetPort: 5005

---

apiVersion: v1
kind: Service
metadata:
  name: flaskapp-deployment-prod
  namespace: dev
  labels:
    app: flask-svc
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
  - port: 5005
    protocol: TCP
    targetPort: 5005

--- #Creation des ingress

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-flask-svc
  namespace: prod
spec:
  defaultBackend:
    service:
      name: flask-svc
      port:
        number: 5005

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-flask-svc
  namespace: preprod
spec:
  defaultBackend:
    service:
      name: flask-svc
      port:
        number: 5005

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-flask-svc
  namespace: dev
spec:
  defaultBackend:
    service:
      name: flask-svc
      port:
        number: 5005

--- #Création des configmaps

apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-app-configmap
  namespace: prod
data:
  DEBUG: "True"
  FLASK_APP: "run.py"
  FLASK_DEBUG: "True"
  SERVER_ADDRESS: "http://localhost:5005/"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-app-configmap
  namespace: preprod
data:
  DEBUG: "True"
  FLASK_APP: "run.py"
  FLASK_DEBUG: "True"
  SERVER_ADDRESS: "http://localhost:5005/"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-app-configmap
  namespace: dev
data:
  DEBUG: "True"
  FLASK_APP: "run.py"
  FLASK_DEBUG: "True"
  SERVER_ADDRESS: "http://localhost:5005/"

--- #Creation des deploiements



