apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
type: Opaque
data:
  STRIPE_PUBLISHABLE_KEY: cGtfdGVzdF81MVAwbUlOQms1NnRxRVp3Y0VnRXZLanVveEJQdnBLZTB6Mklhc1dDdjBWSFlJNzZjZVVXOWRQR01Xb2xsTk1hRFliMzZ1NlZpYlNzV3c4dGU1UHcxWXVUSjAwZWh5YTBheHY=
  STRIPE_SECRET_KEY: c2tfdGVzdF81MVAwbUlOQms1NnRxRVp3Y3dJUXVVdEt6R21FdGEyeThXbUk4NkZtdUFJbjJhT2hYV3NZcTJLZXRlcWRMTnpDODBYNFR5M005WXdHR3FHNURlZWNqZTdMQzAwU3pmYm8yaVU=

